// skills/classroomio-design/components/display/PercentRingProgress.jsx
import React from 'react';
const RADIUS = 45;
const CIRCUMFERENCE = 2 * Math.PI * RADIUS;
export function PercentRingProgress({ value, size = 'small', style }) {
  const clamped = Math.max(0, Math.min(100, value));
  const small = size === 'small';
  const px = small ? 40 : 56;
  return <div style={{ position: 'relative', width: 'fit-content', flexShrink: 0, ...style }}>
    <svg width={px} height={px} viewBox="0 0 100 100" aria-hidden="true" style={{ display: 'block', transform: 'rotate(-90deg)', transformBox: 'fill-box', transformOrigin: 'center' }}>
      <circle cx="50" cy="50" r={RADIUS} fill="none" stroke="#E5E7EB" strokeWidth="8"/>
      <circle cx="50" cy="50" r={RADIUS} fill="none" stroke="#16A34A" strokeWidth="8" strokeLinecap="round" strokeDasharray={CIRCUMFERENCE} strokeDashoffset={CIRCUMFERENCE * (1 - clamped / 100)} style={{ transition: 'stroke-dashoffset 700ms cubic-bezier(0,0,0.2,1)' }}/>
    </svg>
    <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <p style={{ margin: 0, fontFamily: 'var(--font-sans)', fontSize: small ? 10 : 14, lineHeight: 1, color: 'var(--ui-foreground)' }}>{Math.round(clamped)}%</p>
    </div>
  </div>;
}

// packages/ui/src/custom/percent-ring-progress/percent-ring-progress.svelte
<script lang="ts">
  const RING_RADIUS = 45;
  const RING_CIRCUMFERENCE = 2 * Math.PI * RING_RADIUS;

  interface Props {
    /** Progress value from 0 to 100 */
    value: number;
    size?: 'small' | 'default';
  }

  let { value, size = 'small' }: Props = $props();

  const clampedValue = $derived(Math.max(0, Math.min(100, value)));
  const labelPercentage = $derived(Math.round(clampedValue));
  const strokeDashoffset = $derived(RING_CIRCUMFERENCE * (1 - clampedValue / 100));
  const sizeClass = $derived(size === 'small' ? 'ui:size-10' : 'ui:size-14');
  const labelClass = $derived(size === 'small' ? 'ui:text-[10px]' : 'ui:text-sm');
</script>

<div class="ui:relative ui:shrink-0">
  <svg
    class="{sizeClass} ui:-rotate-90"
    style="transform-box: fill-box; transform-origin: center;"
    viewBox="0 0 100 100"
    aria-hidden="true"
  >
    <circle
      cx="50"
      cy="50"
      r={RING_RADIUS}
      fill="none"
      stroke="currentColor"
      stroke-width="8"
      class="ui:text-gray-200 ui:dark:text-gray-700"
    />
    <circle
      cx="50"
      cy="50"
      r={RING_RADIUS}
      fill="none"
      stroke="currentColor"
      stroke-width="8"
      stroke-linecap="round"
      class="ui:text-green-600 ui:transition-[stroke-dashoffset] ui:duration-700 ui:ease-out"
      stroke-dasharray={RING_CIRCUMFERENCE}
      stroke-dashoffset={strokeDashoffset}
    />
  </svg>
  <div class="ui:absolute ui:inset-0 ui:flex ui:flex-col ui:items-center ui:justify-center">
    <p class={labelClass}>{labelPercentage}%</p>
  </div>
</div>
