// packages/ui/src/base/checkbox/checkbox.svelte
<script lang="ts">
  import { Checkbox as CheckboxPrimitive } from 'bits-ui';
  import CheckIcon from '@lucide/svelte/icons/check';
  import MinusIcon from '@lucide/svelte/icons/minus';
  import { cn, type WithoutChildrenOrChild } from '../../tools';

  let {
    ref = $bindable(null),
    checked = $bindable(false),
    indeterminate = $bindable(false),
    class: className,
    ...restProps
  }: WithoutChildrenOrChild<CheckboxPrimitive.RootProps> = $props();
</script>

<CheckboxPrimitive.Root
  bind:ref
  data-slot="checkbox"
  class={cn(
    'ui:border-input ui:dark:bg-input/30 ui:data-[state=checked]:bg-primary ui:data-[state=checked]:text-primary-foreground ui:dark:data-[state=checked]:bg-primary ui:data-[state=checked]:border-primary ui:focus-visible:border-ring ui:focus-visible:ring-ring/50 ui:aria-invalid:ring-destructive/20 ui:dark:aria-invalid:ring-destructive/40 ui:aria-invalid:border-destructive ui:shadow-xs ui:flex ui:size-4 ui:shrink-0 ui:items-center ui:justify-center ui:rounded-[4px] ui:border ui:outline-none ui:transition-shadow ui:focus-visible:ring-[3px] ui:disabled:cursor-not-allowed ui:disabled:opacity-50 peer',
    className
  )}
  bind:checked
  bind:indeterminate
  {...restProps}
>
  {#snippet children({ checked, indeterminate })}
    <div data-slot="checkbox-indicator" class="ui:text-current ui:transition-none">
      {#if checked}
        <CheckIcon class="ui:size-3.5" />
      {:else if indeterminate}
        <MinusIcon class="ui:size-3.5" />
      {/if}
    </div>
  {/snippet}
</CheckboxPrimitive.Root>

// skills/classroomio-design/components/forms/Checkbox.jsx
import React from 'react';
import { Ic, useInteract } from './_ui.js';
export function Checkbox({ checked, defaultChecked = false, indeterminate = false, onChange, disabled, invalid, id, label, style }) {
  const [inner, setInner] = React.useState(defaultChecked);
  const on = checked !== undefined ? checked : inner;
  const { focus, bind } = useInteract();
  const filled = on || indeterminate;
  const box = <button type="button" role="checkbox" id={id} aria-checked={indeterminate ? 'mixed' : on} disabled={disabled} onClick={() => { setInner(!on); onChange && onChange(!on); }} {...bind}
    style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 16, height: 16, padding: 0, flexShrink: 0, boxSizing: 'border-box', borderRadius: 4, border: '1px solid ' + (invalid ? 'var(--ui-destructive)' : filled ? 'var(--ui-primary)' : 'var(--ui-input)'), background: filled ? 'var(--ui-primary)' : 'var(--ui-background)', color: 'var(--ui-primary-foreground)', boxShadow: focus ? 'var(--ui-focus-ring)' : 'var(--ui-shadow-xs)', cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? 0.5 : 1, outline: 'none', transition: 'box-shadow 150ms' }}>
    {on ? Ic('check', 14) : indeterminate ? Ic('minus', 14) : null}
  </button>;
  if (!label) return React.cloneElement(box, { style: { ...box.props.style, ...style } });
  return <label style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 500, color: 'var(--ui-foreground)', cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? 0.5 : 1, ...style }}>{box}{label}</label>;
}
