// packages/ui/src/custom/combo-button/combo-button.svelte
<script lang="ts" module>
  import type { Component } from 'svelte';

  export type ComboButtonItem = {
    /** Stable key, used for the `{#each}` and as a test-id suffix. */
    id: string;
    label: string;
    /** Optional lucide icon component. */
    icon?: Component<{ size?: number | string; class?: string }>;
    /** Shown under the label, e.g. why the item is unavailable. */
    description?: string;
    disabled?: boolean;
    destructive?: boolean;
    onSelect: () => void | Promise<void>;
  };
</script>

<script lang="ts">
  import * as ButtonGroup from '../../base/button-group';
  import * as DropdownMenu from '../../base/dropdown-menu';
  import ChevronDownIcon from '@lucide/svelte/icons/chevron-down';
  import { Button } from '../../base/button';
  import type { ButtonVariant } from '../../base/button';

  interface Props {
    /** The primary half. Label it with the action it performs, not a category. */
    label: string;
    items: ComboButtonItem[];
    icon?: Component<{ size?: number | string; class?: string }>;
    variant?: ButtonVariant;
    size?: 'sm' | 'default' | 'lg';
    disabled?: boolean;
    loading?: boolean;
    /** Accessible name for the chevron, which has no visible text. */
    menuLabel: string;
    align?: 'start' | 'center' | 'end';
    testId?: string;
    onSelect: () => void | Promise<void>;
  }

  let {
    label,
    items,
    icon: Icon,
    variant = 'outline',
    size = 'sm',
    disabled = false,
    loading = false,
    menuLabel,
    align = 'end',
    testId,
    onSelect
  }: Props = $props();

  const iconSize = $derived(size === 'lg' ? 18 : 16);
  const triggerSize = $derived(size === 'sm' ? 'icon-sm' : 'icon');
</script>

<ButtonGroup.Root>
  <Button {variant} {size} {disabled} {loading} {testId} onclick={onSelect}>
    {#if Icon && !loading}
      <Icon size={iconSize} />
    {/if}
    {label}
  </Button>

  <DropdownMenu.Root>
    <DropdownMenu.Trigger>
      {#snippet child({ props })}
        <Button
          {...props}
          type="button"
          {variant}
          size={triggerSize}
          disabled={disabled || loading}
          aria-label={menuLabel}
          testId={testId ? `${testId}-menu` : undefined}
        >
          <ChevronDownIcon size={iconSize} />
        </Button>
      {/snippet}
    </DropdownMenu.Trigger>

    <DropdownMenu.Content {align} class="ui:w-56">
      {#each items as item (item.id)}
        <DropdownMenu.Item
          disabled={item.disabled}
          class={item.destructive ? 'ui:text-destructive ui:focus:text-destructive' : undefined}
          onSelect={item.onSelect}
        >
          {#if item.icon}
            <item.icon size={16} />
          {/if}
          <span class="ui:flex ui:flex-col">
            <span>{item.label}</span>
            {#if item.description}
              <span class="ui:text-muted-foreground ui:text-xs">{item.description}</span>
            {/if}
          </span>
        </DropdownMenu.Item>
      {/each}
    </DropdownMenu.Content>
  </DropdownMenu.Root>
</ButtonGroup.Root>

// skills/classroomio-design/components/forms/ComboButton.jsx
import React from 'react';
import { Ic } from './uiShared.jsx';
import { Button } from './Button.jsx';
import { DropdownMenu } from '../overlays/DropdownMenu.jsx';
export function ComboButton({ label, menuLabel, items = [], icon, variant = 'outline', size = 'sm', disabled = false, loading = false, align = 'end', onSelect, style }) {
  const iconSize = size === 'lg' ? 18 : 16;
  const triggerSize = size === 'sm' ? 'icon-sm' : 'icon';
  const menuItems = items.map((it) => ({
    icon: it.icon,
    disabled: it.disabled,
    variant: it.destructive ? 'destructive' : undefined,
    onSelect: it.onSelect,
    label: <span style={{ display: 'flex', flexDirection: 'column' }}>
      <span>{it.label}</span>
      {it.description && <span style={{ fontSize: 12, color: 'var(--ui-muted-foreground)' }}>{it.description}</span>}
    </span>,
  }));
  return <div role="group" style={{ display: 'flex', width: 'fit-content', alignItems: 'stretch', ...style }}>
    <Button variant={variant} size={size} disabled={disabled} loading={loading} onClick={onSelect} style={{ borderTopRightRadius: 0, borderBottomRightRadius: 0 }}>
      {icon && !loading && <span style={{ display: 'flex' }}>{icon}</span>}
      {label}
    </Button>
    <DropdownMenu align={align} minWidth={224} items={menuItems}
      trigger={<Button variant={variant} size={triggerSize} disabled={disabled || loading} aria-label={menuLabel} style={{ borderTopLeftRadius: 0, borderBottomLeftRadius: 0, borderLeftWidth: 0 }}>{Ic('chevronDown', iconSize)}</Button>}/>
  </div>;
}
