// packages/ui/src/base/field/field.svelte
<script lang="ts" module>
  import { tv, type VariantProps } from 'tailwind-variants';

  export const fieldVariants = tv({
    base: 'ui:group/field ui:data-[invalid=true]:text-destructive ui:flex ui:w-full ui:gap-3',
    variants: {
      orientation: {
        vertical: 'ui:flex-col ui:*:w-full ui:*.sr-only:w-auto',
        horizontal: [
          'ui:flex-row ui:items-center',
          'ui:[&>[data-slot=field-label]]:flex-auto',
          'ui:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px ui:has-[>[data-slot=field-content]]:items-start'
        ],
        responsive: [
          'ui:@md/field-group:flex-row ui:@md/field-group:items-center ui:@md/field-group:[&>*]:w-auto ui:flex-col ui:*:w-full ui:*.sr-only:w-auto',
          'ui:@md/field-group:[&>[data-slot=field-label]]:flex-auto',
          'ui:@md/field-group:has-[>[data-slot=field-content]]:items-start ui:@md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px'
        ]
      }
    },
    defaultVariants: {
      orientation: 'vertical'
    }
  });

  export type FieldOrientation = VariantProps<typeof fieldVariants>['orientation'];
</script>

<script lang="ts">
  import { cn, type WithElementRef } from '../../tools';
  import type { HTMLAttributes } from 'svelte/elements';

  let {
    ref = $bindable(null),
    class: className,
    orientation = 'vertical',
    children,
    ...restProps
  }: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
    orientation?: FieldOrientation;
  } = $props();
</script>

<div
  bind:this={ref}
  role="group"
  data-slot="field"
  data-orientation={orientation}
  class={cn(fieldVariants({ orientation }), className)}
  {...restProps}
>
  {@render children?.()}
</div>

// skills/classroomio-design/components/forms/Field.jsx
import React from 'react';
import { Label } from './Label.jsx';
export function Field({ label, htmlFor, required, description, error, orientation = 'vertical', children, style }) {
  const h = orientation === 'horizontal';
  return <div role="group" data-invalid={!!error || undefined} style={{ display: 'flex', flexDirection: h ? 'row' : 'column', alignItems: h ? 'center' : 'stretch', gap: 12, width: '100%', ...style }}>
    {h && children}
    {(label || description) && <div style={{ display: 'flex', flexDirection: 'column', gap: 6, flex: h ? '1 1 auto' : undefined }}>
      {label && <Label htmlFor={htmlFor} required={required} style={error ? { color: 'var(--ui-destructive)' } : null}>{label}</Label>}
      {h && description && <p style={{ margin: 0, fontSize: 14, lineHeight: 1.5, color: 'var(--ui-muted-foreground)' }}>{description}</p>}
    </div>}
    {!h && children}
    {!h && description && <p style={{ margin: '-4px 0 0', fontSize: 14, lineHeight: 1.5, color: 'var(--ui-muted-foreground)' }}>{description}</p>}
    {error && <div role="alert" style={{ fontSize: 14, color: 'var(--ui-destructive)' }}>{error}</div>}
  </div>;
}
