// packages/ui/src/base/switch/switch.svelte
<script lang="ts">
  import { Switch as SwitchPrimitive } from 'bits-ui';
  import { cn, type WithoutChildrenOrChild } from '../../tools';

  let {
    ref = $bindable(null),
    class: className,
    checked = $bindable(false),
    ...restProps
  }: WithoutChildrenOrChild<SwitchPrimitive.RootProps> = $props();
</script>

<SwitchPrimitive.Root
  bind:ref
  bind:checked
  data-slot="switch"
  class={cn(
    'data-[state=checked]:bg-primary data-[state=unchecked]:bg-input focus-visible:border-ring focus-visible:ring-ring/50 dark:data-[state=unchecked]:bg-input/80 shadow-xs peer inline-flex h-[1.15rem] w-8 shrink-0 items-center rounded-full border border-transparent outline-none transition-all focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50',
    className
  )}
  {...restProps}
>
  <SwitchPrimitive.Thumb
    data-slot="switch-thumb"
    class={cn(
      'bg-background dark:data-[state=unchecked]:bg-foreground dark:data-[state=checked]:bg-primary-foreground pointer-events-none block size-4 rounded-full ring-0 transition-transform data-[state=checked]:translate-x-[calc(100%-2px)] data-[state=unchecked]:translate-x-0'
    )}
  />
</SwitchPrimitive.Root>

// skills/classroomio-design/components/forms/Switch.jsx
import React from 'react';
import { useInteract } from './_ui.js';
export function Switch({ checked, defaultChecked = false, onChange, disabled, id, label, style }) {
  const [inner, setInner] = React.useState(defaultChecked);
  const on = checked !== undefined ? checked : inner;
  const { focus, bind } = useInteract();
  const sw = <button type="button" role="switch" id={id} aria-checked={on} disabled={disabled} onClick={() => { setInner(!on); onChange && onChange(!on); }} {...bind}
    style={{ display: 'inline-flex', alignItems: 'center', width: 32, height: 18.4, padding: 0, flexShrink: 0, boxSizing: 'border-box', borderRadius: 999, border: '1px solid transparent', background: on ? 'var(--ui-primary)' : 'var(--ui-input)', boxShadow: focus ? 'var(--ui-focus-ring)' : 'var(--ui-shadow-xs)', cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? 0.5 : 1, outline: 'none', transition: 'all 150ms' }}>
    <span style={{ display: 'block', width: 16, height: 16, borderRadius: '50%', background: 'var(--ui-background)', transform: on ? 'translateX(14px)' : 'translateX(0)', transition: 'transform 150ms' }}/>
  </button>;
  if (!label) return React.cloneElement(sw, { style: { ...sw.props.style, ...style } });
  return <label style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 500, color: 'var(--ui-foreground)', cursor: 'pointer', ...style }}>{sw}{label}</label>;
}
