// packages/ui/src/base/toggle/toggle.svelte
<script lang="ts" module>
  import { type VariantProps, tv } from 'tailwind-variants';

  export const toggleVariants = tv({
    base: "ui:hover:bg-muted ui:hover:text-muted-foreground ui:data-[state=on]:bg-accent ui:data-[state=on]:text-accent-foreground ui:focus-visible:border-ring ui:focus-visible:ring-ring/50 ui:aria-invalid:ring-destructive/20 ui:dark:aria-invalid:ring-destructive/40 ui:aria-invalid:border-destructive ui:inline-flex ui:items-center ui:justify-center ui:gap-2 ui:rounded-md ui:text-sm ui:font-medium ui:whitespace-nowrap ui:transition-[color,box-shadow] ui:outline-none ui:focus-visible:ring-[3px] ui:disabled:pointer-events-none ui:disabled:opacity-50 ui:[&_svg]:pointer-events-none ui:[&_svg]:shrink-0 ui:[&_svg:not([class*='size-'])]:size-4",
    variants: {
      variant: {
        default: 'ui:bg-transparent',
        outline:
          'ui:border-input ui:hover:bg-accent ui:hover:text-accent-foreground ui:border ui:bg-transparent ui:shadow-xs'
      },
      size: {
        default: 'ui:h-9 ui:min-w-9 ui:px-2',
        sm: 'ui:h-8 ui:min-w-8 ui:px-1.5',
        lg: 'ui:h-10 ui:min-w-10 ui:px-2.5'
      }
    },
    defaultVariants: {
      variant: 'default',
      size: 'default'
    }
  });

  export type ToggleVariant = VariantProps<typeof toggleVariants>['variant'];
  export type ToggleSize = VariantProps<typeof toggleVariants>['size'];
  export type ToggleVariants = VariantProps<typeof toggleVariants>;
</script>

<script lang="ts">
  import { Toggle as TogglePrimitive } from 'bits-ui';
  import { cn } from '../../tools';

  let {
    ref = $bindable(null),
    pressed = $bindable(false),
    class: className,
    size = 'default',
    variant = 'default',
    ...restProps
  }: TogglePrimitive.RootProps & {
    variant?: ToggleVariant;
    size?: ToggleSize;
  } = $props();
</script>

<TogglePrimitive.Root
  bind:ref
  bind:pressed
  data-slot="toggle"
  class={cn(toggleVariants({ variant, size }), className)}
  {...restProps}
/>

// skills/classroomio-design/components/forms/Toggle.jsx
import React from 'react';
import { useInteract, FONT } from './_ui.js';
const SZ = { default: [36, 8], sm: [32, 6], lg: [40, 10] };
export function Toggle({ pressed, defaultPressed = false, onChange, variant = 'default', size = 'default', disabled, children, style, ...rest }) {
  const [inner, setInner] = React.useState(defaultPressed);
  const on = pressed !== undefined ? pressed : inner;
  const { hover, focus, bind } = useInteract();
  const [h, px] = SZ[size] || SZ.default;
  return <button type="button" aria-pressed={on} disabled={disabled} onClick={() => { setInner(!on); onChange && onChange(!on); }} {...bind} {...rest}
    style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8, height: h, minWidth: h, padding: `0 ${px}px`, boxSizing: 'border-box', borderRadius: 'var(--ui-radius-md)', fontFamily: FONT, fontSize: 14, fontWeight: 500, whiteSpace: 'nowrap', cursor: 'pointer', outline: 'none', transition: 'color 150ms, box-shadow 150ms', opacity: disabled ? 0.5 : 1,
      border: variant === 'outline' ? '1px solid var(--ui-input)' : '1px solid transparent', boxShadow: focus ? 'var(--ui-focus-ring)' : variant === 'outline' ? 'var(--ui-shadow-xs)' : 'none',
      background: on ? 'var(--ui-accent)' : hover ? (variant === 'outline' ? 'var(--ui-accent)' : 'var(--ui-muted)') : 'transparent',
      color: on ? 'var(--ui-accent-foreground)' : hover && variant !== 'outline' ? 'var(--ui-muted-foreground)' : 'var(--ui-foreground)', ...style }}>{children}</button>;
}
export function ToggleGroup({ items = [], value, defaultValue, onChange, type = 'single', variant = 'default', size = 'default', style }) {
  const [inner, setInner] = React.useState(defaultValue ?? (type === 'multiple' ? [] : undefined));
  const cur = value !== undefined ? value : inner;
  const isOn = (v) => type === 'multiple' ? (cur || []).includes(v) : cur === v;
  const set = (v) => { const n = type === 'multiple' ? (isOn(v) ? cur.filter(x => x !== v) : [...(cur || []), v]) : (cur === v ? undefined : v); setInner(n); onChange && onChange(n); };
  return <div role="group" style={{ display: 'flex', width: 'fit-content', alignItems: 'center', borderRadius: 'var(--ui-radius-md)', boxShadow: variant === 'outline' ? 'var(--ui-shadow-xs)' : 'none', ...style }}>
    {items.map((it, i) => <Toggle key={it.value} variant={variant} size={size} pressed={isOn(it.value)} onChange={() => set(it.value)} aria-label={it.ariaLabel}
      style={{ flex: 1, minWidth: 0, boxShadow: 'none', borderRadius: i === 0 ? 'var(--ui-radius-md) 0 0 var(--ui-radius-md)' : i === items.length - 1 ? '0 var(--ui-radius-md) var(--ui-radius-md) 0' : 0, borderLeftWidth: variant === 'outline' && i > 0 ? 0 : undefined }}>{it.label}</Toggle>)}
  </div>;
}
