// packages/ui/src/custom/pricing-card/pricing-card.svelte
<script lang="ts">
  import CheckIcon from '@lucide/svelte/icons/check';
  import { Badge } from '../../base/badge';
  import { Button } from '../../base/button';
  import { HoverableItem, PremiumIcon } from '../moving-icons';
  import type { PlanData } from './types';
  import { cn } from '../../tools';

  interface Props {
    plan: PlanData;
    isPopular?: boolean;
    isYearlyPlan?: boolean;
    isLoadingPlan?: string | null;
    planName: string;
    handleClick?: ((plan: PlanData, planName: string) => void) | (() => void);
    popularLabel?: string;
    perOrgLabel?: string;
    ctaLabel?: string;
    isDisabled?: boolean;
    className?: string;
  }

  let {
    className,
    plan,
    isPopular = false,
    isYearlyPlan = false,
    isLoadingPlan = null,
    planName,
    handleClick = () => {},
    popularLabel = 'Popular',
    perOrgLabel = 'Per Organization',
    ctaLabel = plan.CTA.DASHBOARD_LABEL,
    isDisabled = plan.CTA.IS_DISABLED
  }: Props = $props();

  const isLoading = $derived(isLoadingPlan === planName);
</script>

<div
  class={cn(
    'ui:relative ui:flex ui:max-w-sm ui:flex-col ui:rounded-lg ui:border ui:border-border ui:bg-card ui:p-4 ui:sm:p-8',
    className
  )}
>
  {#if isPopular}
    <Badge
      variant="default"
      class="ui:absolute ui:-top-3 ui:left-1/2 ui:-translate-x-1/2 ui:bg-linear-to-r ui:from-pink-500 ui:to-orange-500 ui:px-4 ui:py-1"
    >
      {popularLabel}
    </Badge>
  {/if}

  <!-- Plan Header -->
  <div class="ui:mb-4">
    <h3 class="ui:mb-2 ui:text-xl ui:font-bold ui:tracking-tight ui:text-foreground">
      {plan.NAME}
    </h3>
    <div class="ui:mb-1 ui:flex ui:items-baseline ui:gap-1">
      <span class="ui:text-xl ui:font-medium ui:text-foreground">
        {plan.PRICE.CURRENCY}{isYearlyPlan ? plan.PRICE.YEARLY : plan.PRICE.MONTHLY}
      </span>
    </div>
    <p class="ui:text-sm ui:font-medium ui:text-muted-foreground">{perOrgLabel}</p>
  </div>

  <!-- CTA Button -->
  <div class="ui:mb-4">
    <HoverableItem>
      {#snippet children(isHovered: boolean)}
        <Button
          variant={isPopular ? 'default' : 'outline'}
          class="ui:w-full ui:py-3 ui:text-base ui:transition-all ui:sm:py-4"
          disabled={isDisabled || isLoading}
          loading={isLoading}
          onclick={() => {
            if (isLoading) return;
            handleClick(plan, planName);
          }}
        >
          {#if isPopular}
            <PremiumIcon size={18} {isHovered} class="ui:mr-2" />
          {/if}
          {ctaLabel}
        </Button>
      {/snippet}
    </HoverableItem>
  </div>

  <!-- Features List -->
  <div class="ui:flex-1">
    <p class="ui:mb-4 ui:text-sm ui:font-semibold ui:text-foreground">What's included:</p>
    <ul class="ui:space-y-2">
      {#each plan.FEATURES as feature}
        <li class="ui:flex ui:items-start ui:gap-3">
          <div class="ui:mt-1 ui:flex ui:size-5 ui:shrink-0 ui:items-center ui:justify-center ui:rounded-full">
            <CheckIcon class="ui:size-3.5" />
          </div>
          <span class="ui:text-sm ui:leading-relaxed ui:text-muted-foreground">
            {feature}
          </span>
        </li>
      {/each}
    </ul>
  </div>
</div>

// skills/classroomio-design/components/surfaces/PricingCard.jsx
import React from 'react';
import { Ic, FONT } from '../forms/_ui.js';
import { Button } from '../forms/Button.jsx';

const GRADIENT = 'linear-gradient(to right, #ec4899, #f97316)';

export function PricingCard({ plan, isPopular = false, isYearlyPlan = false, isLoadingPlan = null, planName, onClick, popularLabel = 'Popular', perOrgLabel = 'Per Organization', ctaLabel, isDisabled, featuresLabel = "What's included:", style }) {
  const isLoading = isLoadingPlan === planName;
  const price = isYearlyPlan ? plan.PRICE.YEARLY : plan.PRICE.MONTHLY;
  return <div style={{ position: 'relative', display: 'flex', flexDirection: 'column', maxWidth: 384, boxSizing: 'border-box', padding: 32, borderRadius: 'var(--ui-radius-lg)', border: '1px solid var(--ui-border)', background: 'var(--ui-card)', fontFamily: FONT, ...style }}>
    {isPopular && <span style={{ position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)', display: 'inline-flex', alignItems: 'center', whiteSpace: 'nowrap', padding: '4px 16px', borderRadius: 999, background: GRADIENT, color: '#fff', fontSize: 12, lineHeight: '16px', fontWeight: 500 }}>{popularLabel}</span>}
    <div style={{ marginBottom: 16 }}>
      <h3 style={{ margin: '0 0 8px', fontSize: 20, lineHeight: '28px', fontWeight: 700, letterSpacing: '-0.025em', color: 'var(--ui-foreground)' }}>{plan.NAME}</h3>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 4, marginBottom: 4 }}>
        <span style={{ fontSize: 20, lineHeight: '28px', fontWeight: 500, color: 'var(--ui-foreground)' }}>{plan.PRICE.CURRENCY}{price}</span>
      </div>
      <p style={{ margin: 0, fontSize: 14, fontWeight: 500, color: 'var(--ui-muted-foreground)' }}>{perOrgLabel}</p>
    </div>
    <div style={{ marginBottom: 16 }}>
      <Button variant={isPopular ? 'default' : 'outline'} loading={isLoading} disabled={isDisabled ?? plan.CTA.IS_DISABLED} onClick={() => { if (!isLoading && onClick) onClick(plan, planName); }} style={{ width: '100%', height: 'auto', padding: '16px 16px', fontSize: 16 }}>
        {isPopular && Ic('sparkles', 18)}
        {ctaLabel ?? plan.CTA.DASHBOARD_LABEL}
      </Button>
    </div>
    <div style={{ flex: 1 }}>
      <p style={{ margin: '0 0 16px', fontSize: 14, fontWeight: 600, color: 'var(--ui-foreground)' }}>{featuresLabel}</p>
      <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
        {plan.FEATURES.map((feature) => <li key={feature} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
          <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, width: 20, height: 20, marginTop: 4, color: 'var(--ui-foreground)' }}>{Ic('check', 14)}</span>
          <span style={{ fontSize: 14, lineHeight: 1.625, color: 'var(--ui-muted-foreground)' }}>{feature}</span>
        </li>)}
      </ul>
    </div>
  </div>;
}
