// packages/ui/src/custom/pricing/pricing-card.svelte
<script lang="ts">
  import CheckIcon from '@lucide/svelte/icons/check';
  import { Button } from '../../base/button';
  import { Badge } from '../../base/badge';
  import { PremiumIcon, HoverableItem } from '../moving-icons';
  import type { Plan } from './types';

  let {
    plan,
    planName,
    isYearlyPlan,
    isDashboard = false,
    onSelect,
    ...rest
  } = $props<{
    plan: Plan;
    planName: string;
    isYearlyPlan: boolean;
    isLoading?: boolean;
    isDashboard?: boolean;
    onSelect?: (plan: Plan, planName: string) => void;
    [key: string]: any;
  }>();

  const isPopular = $derived(planName === 'EARLY_ADOPTER');
</script>

<div class="relative flex max-w-sm flex-col rounded-lg p-6 {isPopular ? 'animate-gradient-border' : 'border '}">
  {#if isPopular}
    <Badge
      variant="default"
      class="absolute -top-3 left-1/2 -translate-x-1/2 bg-linear-to-r from-pink-500 to-orange-500"
    >
      Popular
    </Badge>
  {/if}
  <div class="mb-4">
    <h3 class="mb-2 text-lg font-semibold">
      {plan?.NAME}
    </h3>
    <div class="mb-1 flex items-baseline gap-1">
      <span class="text-xl">
        {plan?.PRICE?.CURRENCY}
        {isYearlyPlan ? plan?.PRICE?.YEARLY : plan?.PRICE?.MONTHLY}
      </span>
    </div>
    <p class="text-sm text-gray-500">Per Organization</p>
  </div>

  <HoverableItem>
    {#snippet children(isHovered)}
      <Button
        {...rest}
        variant={isPopular ? 'default' : 'outline'}
        class="mb-6 w-full"
        disabled={plan?.CTA?.IS_DISABLED || isLoading}
        loading={isLoading}
        href={!isDashboard ? plan?.CTA?.LINK : undefined}
        target={!isDashboard ? '_blank' : undefined}
        onclick={(e) => {
          if (isLoading) return;
          if (isDashboard) {
            onSelect?.(plan, planName);
          } else if (onSelect) {
            onSelect(plan, planName);
          }
        }}
      >
        {#if isPopular}
          <PremiumIcon size={16} {isHovered} />
        {/if}
        {isDashboard ? plan?.CTA?.DASHBOARD_LABEL : plan?.CTA?.LABEL}
      </Button>
    {/snippet}
  </HoverableItem>

  <ul class="space-y-3">
    {#each plan?.FEATURES as feature}
      <li class="flex items-start gap-2">
        <CheckIcon class="mt-0.5 size-4 shrink-0" />
        <span class="text-sm leading-relaxed">
          {feature}
        </span>
      </li>
    {/each}
  </ul>
</div>

// skills/classroomio-design/components/surfaces/PricingCard.jsx
import React from 'react';
import { Ic, FONT } from '../forms/_ui.js';
import { Button } from '../forms/Button.jsx';

const GRADIENT = 'linear-gradient(to right, #ec4899, #f97316)';

export function PricingCard({ plan, isPopular = false, isYearlyPlan = false, isLoadingPlan = null, planName, onClick, popularLabel = 'Popular', perOrgLabel = 'Per Organization', ctaLabel, isDisabled, featuresLabel = "What's included:", style }) {
  const isLoading = isLoadingPlan === planName;
  const price = isYearlyPlan ? plan.PRICE.YEARLY : plan.PRICE.MONTHLY;
  return <div style={{ position: 'relative', display: 'flex', flexDirection: 'column', maxWidth: 384, boxSizing: 'border-box', padding: 32, borderRadius: 'var(--ui-radius-lg)', border: '1px solid var(--ui-border)', background: 'var(--ui-card)', fontFamily: FONT, ...style }}>
    {isPopular && <span style={{ position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)', display: 'inline-flex', alignItems: 'center', whiteSpace: 'nowrap', padding: '4px 16px', borderRadius: 999, background: GRADIENT, color: '#fff', fontSize: 12, lineHeight: '16px', fontWeight: 500 }}>{popularLabel}</span>}
    <div style={{ marginBottom: 16 }}>
      <h3 style={{ margin: '0 0 8px', fontSize: 20, lineHeight: '28px', fontWeight: 700, letterSpacing: '-0.025em', color: 'var(--ui-foreground)' }}>{plan.NAME}</h3>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 4, marginBottom: 4 }}>
        <span style={{ fontSize: 20, lineHeight: '28px', fontWeight: 500, color: 'var(--ui-foreground)' }}>{plan.PRICE.CURRENCY}{price}</span>
      </div>
      <p style={{ margin: 0, fontSize: 14, fontWeight: 500, color: 'var(--ui-muted-foreground)' }}>{perOrgLabel}</p>
    </div>
    <div style={{ marginBottom: 16 }}>
      <Button variant={isPopular ? 'default' : 'outline'} loading={isLoading} disabled={isDisabled ?? plan.CTA.IS_DISABLED} onClick={() => { if (!isLoading && onClick) onClick(plan, planName); }} style={{ width: '100%', height: 'auto', padding: '16px 16px', fontSize: 16 }}>
        {isPopular && Ic('sparkles', 18)}
        {ctaLabel ?? plan.CTA.DASHBOARD_LABEL}
      </Button>
    </div>
    <div style={{ flex: 1 }}>
      <p style={{ margin: '0 0 16px', fontSize: 14, fontWeight: 600, color: 'var(--ui-foreground)' }}>{featuresLabel}</p>
      <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
        {plan.FEATURES.map((feature) => <li key={feature} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
          <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, width: 20, height: 20, marginTop: 4, color: 'var(--ui-foreground)' }}>{Ic('check', 14)}</span>
          <span style={{ fontSize: 14, lineHeight: 1.625, color: 'var(--ui-muted-foreground)' }}>{feature}</span>
        </li>)}
      </ul>
    </div>
  </div>;
}
