// apps/classroomio-com/src/lib/NotFound/NotFound.svelte
<script>
  import { goto } from '$app/navigation';

  export let isOrg = false;
  export let className = '';

  function handleClick() {
    if (!isOrg) {
      return goto('/');
    }

    return goto('https://classroomio.com');
  }
</script>

<div class="{className} min-h-[80vh] flex items-center justify-center flex-col w-screen">
  <img src="https://brand.cdn.clsrio.com/404.png" alt="classroomio_error_image" />

  <div class="flex flex-col items-center justify-center dark:text-white gap-3 w-4/5 lg:w-2/5">
    <p class="text-4xl dark:text-white font-semibold mb-5">
      {#if isOrg}
        Organization doesn't exist!
      {:else}
        Page not found
      {/if}
    </p>
    <p class=" text-gray-700 text-lg text-center dark:text-white mb-5">
      The page you are looking for doesn't exist or has been moved. Please go back to the homepage.
    </p>

    <button
      class="text-base rounded-md bg-black transition-all delay-100 hover:shadow-xl hover:scale-95 px-6 py-4 font-semibold text-white lg:px-7 lg:py-3 lg:text-lg"
      on:click={handleClick}
    >
      Go Home
    </button>
  </div>
</div>

// apps/docs-v2/src/components/not-found.tsx
import { Link } from '@tanstack/react-router';
import { HomeLayout } from 'fumadocs-ui/layouts/home';

export function NotFound() {
  return (
    <HomeLayout
      nav={{
        title: 'ClassroomIO'
      }}
      className="justify-center py-32 text-center"
    >
      <div className="flex flex-col items-center gap-4">
        <h1 className="text-fd-muted-foreground text-6xl font-bold">404</h1>
        <h2 className="text-2xl font-semibold">Page Not Found</h2>
        <p className="text-fd-muted-foreground max-w-md">
          The page you are looking for might have been removed, had its name changed, or is
          temporarily unavailable.
        </p>
        <Link
          to="/"
          className="bg-fd-primary text-fd-primary-foreground mt-4 rounded-lg px-4 py-2 text-sm font-medium transition-opacity hover:opacity-90"
        >
          Back to Home
        </Link>
      </div>
    </HomeLayout>
  );
}
