// packages/ui/src/base/badge/badge.svelte
<script lang="ts" module>
  import { type VariantProps, tv } from 'tailwind-variants';

  export const badgeVariants = tv({
    base: 'ui:focus-visible:border-ring ui:focus-visible:ring-ring/50 ui:aria-invalid:ring-destructive/20 ui:dark:aria-invalid:ring-destructive/40 ui:aria-invalid:border-destructive ui:inline-flex ui:w-fit ui:shrink-0 ui:items-center ui:justify-center ui:gap-1 ui:overflow-hidden ui:whitespace-nowrap ui:rounded-full ui:border ui:px-2 ui:py-0.5 ui:text-xs ui:font-medium ui:transition-[color,box-shadow] ui:focus-visible:ring-[3px] ui:[&>svg]:pointer-events-none ui:[&>svg]:size-3',
    variants: {
      variant: {
        default: 'ui:bg-primary ui:text-primary-foreground ui:[a&]:hover:bg-primary/90 ui:border-transparent',
        secondary: 'ui:bg-secondary ui:text-secondary-foreground ui:[a&]:hover:bg-secondary/90 ui:border-transparent',
        destructive:
          'ui:bg-destructive ui:[a&]:hover:bg-destructive/90 ui:focus-visible:ring-destructive/20 ui:dark:focus-visible:ring-destructive/40 ui:dark:bg-destructive/70 ui:border-transparent ui:text-white',
        warning:
          'ui:bg-amber-600 ui:text-white ui:[a&]:hover:bg-amber-600/90 ui:border-transparent ui:dark:bg-amber-500 ui:dark:text-amber-950',
        success:
          'ui:bg-emerald-600 ui:text-white ui:[a&]:hover:bg-emerald-600/90 ui:border-transparent ui:dark:bg-emerald-500 ui:dark:text-emerald-950',
        outline: 'ui:text-foreground ui:[a&]:hover:bg-accent ui:[a&]:hover:text-accent-foreground'
      }
    },
    defaultVariants: {
      variant: 'default'
    }
  });

  export type BadgeVariant = VariantProps<typeof badgeVariants>['variant'];
</script>

<script lang="ts">
  import type { HTMLAnchorAttributes } from 'svelte/elements';
  import { cn, type WithElementRef } from '../../tools';

  let {
    ref = $bindable(null),
    href,
    class: className,
    variant = 'default',
    children,
    ...restProps
  }: WithElementRef<HTMLAnchorAttributes> & {
    variant?: BadgeVariant;
  } = $props();
</script>

<svelte:element
  this={href ? 'a' : 'span'}
  bind:this={ref}
  data-slot="badge"
  {href}
  class={cn(badgeVariants({ variant }), className)}
  {...restProps}
>
  {@render children?.()}
</svelte:element>

// skills/classroomio-design/components/display/Badge.jsx
import React from 'react';
const V = {
  default: { background: 'var(--ui-primary)', color: 'var(--ui-primary-foreground)', borderColor: 'transparent' },
  secondary: { background: 'var(--ui-secondary)', color: 'var(--ui-secondary-foreground)', borderColor: 'transparent' },
  destructive: { background: 'var(--ui-destructive)', color: '#fff', borderColor: 'transparent' },
  warning: { background: '#D97706', color: '#fff', borderColor: 'transparent' },
  success: { background: '#059669', color: '#fff', borderColor: 'transparent' },
  outline: { background: 'transparent', color: 'var(--ui-foreground)', borderColor: 'var(--ui-border)' },
};
export function Badge({ variant = 'default', href, children, style }) {
  const Tag = href ? 'a' : 'span';
  return <Tag href={href} style={{ display: 'inline-flex', width: 'fit-content', flexShrink: 0, alignItems: 'center', justifyContent: 'center', gap: 4, overflow: 'hidden', whiteSpace: 'nowrap', borderRadius: 999, border: '1px solid', padding: '2px 8px', fontFamily: 'var(--font-sans)', fontSize: 12, lineHeight: '16px', fontWeight: 500, textDecoration: 'none', ...(V[variant] || V.default), ...style }}>{children}</Tag>;
}
