// packages/ui/src/base/spinner/spinner.svelte
<script lang="ts">
  import { cn } from '../../tools';
  import Loader2Icon from '@lucide/svelte/icons/loader-2';
  import type { ComponentProps } from 'svelte';

  let { class: className, ...restProps }: ComponentProps<typeof Loader2Icon> = $props();
</script>

<Loader2Icon role="status" aria-label="Loading" class={cn('size-4 animate-spin', className)} {...restProps} />

// skills/classroomio-design/components/display/Spinner.jsx
import React from 'react';
import { Ic } from '../forms/_ui.js';
export function Spinner({ size = 16, color = 'currentColor', style }) {
  return <span role="status" aria-label="Loading" style={{ display: 'inline-flex', color, ...style }}>{Ic('loader', size, { animation: 'ui-spin 1s linear infinite' })}</span>;
}
