// skills/classroomio-design/components/display/Chip.jsx
import React from 'react';
import { Badge } from './Badge.jsx';
export function Chip({ value = 0, style }) {
  return <Badge variant="outline" style={{ height: 20, minWidth: 20, boxSizing: 'border-box', padding: '0 4px', borderRadius: 999, fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums', ...style }}>{value}</Badge>;
}

// packages/ui/src/custom/chip/chip.svelte
<script lang="ts">
  import { Badge } from '../../base/badge';
  import { cn } from '../../tools';

  interface Props {
    value?: number;
    className?: string;
  }

  let { value = 0, className = '' }: Props = $props();
</script>

<Badge class={cn('h-5 min-w-5 rounded-full px-1 font-mono tabular-nums', className)} variant="outline">
  {value}
</Badge>
