// skills/classroomio-design/components/display/CircularProgress.jsx
import React from 'react';
export function CircularProgress({ value, size = 20, strokeWidth = 2, progressColor = 'var(--ui-primary)', trackColor = 'var(--ui-muted)', style }) {
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const clamped = Math.max(0, Math.min(100, value));
  const offset = circumference - (clamped / 100) * circumference;
  const center = size / 2;
  return <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} role="progressbar" aria-valuenow={clamped} aria-valuemin={0} aria-valuemax={100} style={{ flexShrink: 0, transform: 'rotate(-90deg)', ...style }}>
    <circle cx={center} cy={center} r={radius} fill="none" stroke={trackColor} strokeWidth={strokeWidth}/>
    <circle cx={center} cy={center} r={radius} fill="none" stroke={progressColor} strokeWidth={strokeWidth} strokeDasharray={circumference} strokeDashoffset={offset} strokeLinecap="round" style={{ transition: 'all 300ms' }}/>
  </svg>;
}

// packages/ui/src/custom/circular-progress/circular-progress.svelte
<script lang="ts">
  import { cn } from '../../utils';

  interface Props {
    /** Progress value from 0 to 100 */
    value: number;
    /** Size of the circular progress in pixels */
    size?: number;
    /** Stroke width of the progress ring */
    strokeWidth?: number;
    /** Additional CSS classes */
    class?: string;
    /** Color class for the progress stroke (e.g. 'stroke-primary') */
    progressClass?: string;
    /** Color class for the background track (e.g. 'stroke-muted') */
    trackClass?: string;
  }

  let {
    value,
    size = 20,
    strokeWidth = 2,
    class: className = '',
    progressClass = 'stroke-primary',
    trackClass = 'stroke-muted'
  }: Props = $props();

  const radius = $derived((size - strokeWidth) / 2);
  const circumference = $derived(2 * Math.PI * radius);
  const clampedValue = $derived(Math.max(0, Math.min(100, value)));
  const offset = $derived(circumference - (clampedValue / 100) * circumference);
  const center = $derived(size / 2);
</script>

<svg
  width={size}
  height={size}
  viewBox={`0 0 ${size} ${size}`}
  class={cn('ui:-rotate-90 ui:shrink-0', className)}
  aria-valuenow={clampedValue}
  aria-valuemin={0}
  aria-valuemax={100}
  role="progressbar"
>
  <circle
    cx={center}
    cy={center}
    r={radius}
    fill="none"
    stroke-width={strokeWidth}
    class={cn('ui:transition-all', trackClass)}
  />
  <circle
    cx={center}
    cy={center}
    r={radius}
    fill="none"
    stroke-width={strokeWidth}
    stroke-dasharray={circumference}
    stroke-dashoffset={offset}
    stroke-linecap="round"
    class={cn('ui:transition-all ui:duration-300', progressClass)}
  />
</svg>
