// skills/classroomio-design/components/forms/CopyButton.jsx
import React from 'react';
import { Ic } from './uiShared.jsx';
import { Button } from './Button.jsx';
function Pop({ duration, children }) {
  const ref = React.useRef(null);
  React.useEffect(() => { ref.current && ref.current.animate && ref.current.animate([{ transform: 'scale(0.85)', opacity: 0 }, { transform: 'scale(1)', opacity: 1 }], { duration, easing: 'ease-out' }); }, []);
  return <span ref={ref} style={{ display: 'inline-flex' }}>{children}</span>;
}
export function CopyButton({ text, icon, animationDuration = 500, variant = 'ghost', size = 'icon', onCopy, children, style, ...rest }) {
  const [status, setStatus] = React.useState();
  const timer = React.useRef(null);
  React.useEffect(() => () => clearTimeout(timer.current), []);
  const copy = async () => {
    let next = 'success';
    try { await navigator.clipboard.writeText(text); } catch (e) { next = 'failure'; }
    setStatus(next);
    clearTimeout(timer.current);
    timer.current = setTimeout(() => setStatus(undefined), 500);
    onCopy && onCopy(next);
  };
  const resolved = size === 'icon' && children ? 'default' : size;
  const glyph = status === 'success' ? Ic('check', 16) : status === 'failure' ? Ic('x', 16) : icon || Ic('copy', 16);
  return <Button {...rest} variant={variant} size={resolved} tabIndex={-1} name="copy" aria-label={status === 'success' ? 'Copied' : status === 'failure' ? 'Failed to copy' : 'Copy'} onClick={copy} style={style}>
    <Pop key={status || 'idle'} duration={animationDuration}>{glyph}</Pop>
    {children}
  </Button>;
}

// packages/ui/src/base/copy-button/copy-button.svelte
<script lang="ts">
  import { Button } from '../button';
  import { UseClipboard } from '../../use-clipboard.svelte';
  import { cn } from '../../utils.js';
  import CheckIcon from '@lucide/svelte/icons/check';
  import CopyIcon from '@lucide/svelte/icons/copy';
  import XIcon from '@lucide/svelte/icons/x';
  import { scale } from 'svelte/transition';
  import type { CopyButtonProps } from './types';

  let {
    ref = $bindable(null),
    text,
    icon,
    animationDuration = 500,
    variant = 'ghost',
    size = 'icon',
    onCopy,
    class: className,
    tabindex = -1,
    children,
    ...rest
  }: CopyButtonProps = $props();

  const resolvedSize = $derived(size === 'icon' && children ? 'default' : size);

  const clipboard = new UseClipboard();
</script>

<Button
  {...rest}
  bind:ref
  {variant}
  size={resolvedSize}
  {tabindex}
  class={cn('ui:flex ui:items-center ui:gap-2', className)}
  type="button"
  name="copy"
  onclick={async () => {
    const status = await clipboard.copy(text);

    onCopy?.(status);
  }}
>
  {#if clipboard.status === 'success'}
    <div in:scale={{ duration: animationDuration, start: 0.85 }}>
      <CheckIcon tabindex={-1} />
      <span class="sr-only">Copied</span>
    </div>
  {:else if clipboard.status === 'failure'}
    <div in:scale={{ duration: animationDuration, start: 0.85 }}>
      <XIcon tabindex={-1} />
      <span class="sr-only">Failed to copy</span>
    </div>
  {:else}
    <div in:scale={{ duration: animationDuration, start: 0.85 }}>
      {#if icon}
        {@render icon()}
      {:else}
        <CopyIcon tabindex={-1} />
      {/if}
      <span class="sr-only">Copy</span>
    </div>
  {/if}
  {@render children?.()}
</Button>
