// skills/classroomio-design/components/forms/PricingToggle.jsx
import React from 'react';
import { Ic, FONT } from './_ui.js';

function Period({ active, onClick, children }) {
  const [hover, setHover] = React.useState(false);
  return <button type="button" onClick={onClick} onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}
    style={{ cursor: 'pointer', border: 0, borderRadius: 999, padding: '4px 12px', fontFamily: FONT, fontSize: 14, lineHeight: '20px', fontWeight: 500, transition: 'all 500ms ease-in-out', background: active ? '#E5E7EB' : 'transparent', color: active ? '#111827' : hover ? 'var(--ui-accent-foreground)' : 'var(--ui-muted-foreground)' }}>{children}</button>;
}

export function PricingToggle({ isYearly, defaultYearly = false, onToggle, monthlyLabel = 'Monthly', yearlyLabel = 'Annually', saveLabel = 'Save 2 months', style }) {
  const [inner, setInner] = React.useState(defaultYearly);
  const yearly = isYearly !== undefined ? isYearly : inner;
  const set = (value) => { setInner(value); onToggle && onToggle(value); };
  return <div style={{ position: 'relative', zIndex: 10, display: 'flex', alignItems: 'center', width: 'fit-content', maxWidth: '100%', margin: '0 auto', padding: 4, boxSizing: 'border-box', borderRadius: 999, border: '1px solid var(--ui-border)', background: '#fff', ...style }}>
    <Period active={!yearly} onClick={() => set(false)}>{monthlyLabel}</Period>
    <Period active={yearly} onClick={() => set(true)}>{yearlyLabel}</Period>
    {saveLabel && <span style={{ position: 'absolute', top: -12, right: -16, transform: 'rotate(5deg)', display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 8px', borderRadius: 999, background: 'linear-gradient(to right, #ec4899, #f97316)', color: '#fff', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)', whiteSpace: 'nowrap', fontSize: 10, lineHeight: '16px', fontWeight: 700 }}>
      {Ic('sparkles', 8)}{saveLabel}
    </span>}
  </div>;
}

// packages/ui/src/custom/pricing-toggle/pricing-toggle.svelte
<script lang="ts">
  import { Badge } from '../../base/badge';
  import { HoverableItem, PremiumIcon } from '../moving-icons';

  interface Props {
    isYearly?: boolean;
    monthlyLabel?: string;
    yearlyLabel?: string;
    saveLabel?: string;
    onToggle?: (isYearly: boolean) => void;
  }

  let {
    isYearly = $bindable(false),
    monthlyLabel = 'Monthly',
    yearlyLabel = 'Annually',
    saveLabel = 'Save 2 months',
    onToggle
  }: Props = $props();

  function handleToggle(value: boolean) {
    isYearly = value;
    onToggle?.(value);
  }
</script>

{#snippet period_button(isActive: boolean, isMonth: boolean)}
  <button
    type="button"
    class="ui:cursor-pointer ui:rounded-full ui:px-3 ui:py-1 ui:text-sm ui:font-medium ui:transition-all ui:duration-500 ui:ease-in-out {isActive
      ? 'ui:bg-gray-200 ui:text-gray-900'
      : 'ui:text-muted-foreground ui:hover:text-accent-foreground'}"
    onclick={() => handleToggle(isMonth ? false : true)}
  >
    {isMonth ? monthlyLabel : yearlyLabel}
  </button>
{/snippet}

<div
  class="ui:relative ui:z-10 ui:mx-auto ui:flex ui:w-fit ui:max-w-full ui:items-center ui:rounded-full ui:border ui:p-1 ui:bg-white ui:dark:bg-slate-950 ui:dark:border-slate-800"
>
  {@render period_button(!isYearly, true)}

  {@render period_button(isYearly, false)}

  {#if saveLabel}
    <HoverableItem>
      {#snippet children(isHovered)}
        <Badge
          variant="default"
          class="ui:absolute ui:-top-3 ui:right-0 ui:rotate-5 ui:shadow-2xl ui:bg-linear-to-r ui:from-pink-500 ui:to-orange-500 ui:px-2 ui:py-0.5 ui:sm:-right-4"
        >
          <PremiumIcon size={8} {isHovered} class="ui:text-white! ui:mr-1" />
          <span class="ui:text-[10px] ui:font-bold ui:text-white">{saveLabel}</span>
        </Badge>
      {/snippet}
    </HoverableItem>
  {/if}
</div>
